#Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [6]:
def reverse_number(a):
    """ Returns a number with inversed digits of argument.

    Args:
        a (int): input number.
    """
    result = str(a if a > 0 else -a)
    return int(result[::-1])

print(reverse_number(123))
print(reverse_number(120))
print(reverse_number(-123))

321
21
321


#Выколотый квадрат


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [1]:
def make_square(n):
    """ Draws a square with n-length side.

    Args:
        n (int): length of the side.
    """
    if n < 2:
        raise ValueError("Length of side must be larger than 1")

    print('* ' + ' * '*(n - 2) + ' *') # print top
    for i in range(1, n - 1):
        print('* ' + '   '*(n - 2) + ' *') # print sides
    print('* ' + ' * '*(n - 2) + ' *') # print bottom
    
make_square(5)

*  *  *  *  *
*           *
*           *
*           *
*  *  *  *  *


#Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

In [19]:
def permutations(nums):
    """ Returns all permutations of <nums> array.

    Args:
        nums (array<int>): Array of nums, e.g.: [1, 2, 3].
    
    Algorithm desc:
    All numbers from the list are alternately inserted into the zero index
    (the first cycle). For each number in the zero index, a cycle is started
    from the 1st to the last index (the second cycle) and all numbers except
    the current one from the zero index (the third cycle) are replaced there.
    """
    result_set = set()
    for i in range(0, len(nums)):
        arr = nums.copy()
        arr[0], arr[i] = arr[i], arr[0]
        result_set.add(tuple(arr))
        
        for j in range(1, len(nums)):
            for k in range(0, len(nums)):
                if k == i:
                    continue
                temp = arr.copy()
                temp[j], temp[k] = temp[k], temp[j]
                result_set.add(tuple(temp))
            
    result = []
    for t in result_set:
        result.append(list(t))
        
    return result

print(permutations([1, 2, 3]))
print(permutations([0, 1]))
print(permutations([1]))

[[1, 3, 2], [1, 2, 3], [2, 1, 3], [3, 2, 1], [3, 1, 2], [2, 3, 1]]
[[0, 1], [1, 0]]
[[1]]


### Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [22]:
def almost_double_factorial(n):
  """ Returns the multipllication of even numbers not exceeding n.

  Args:
      n (int): Upper bound of numbers.

  Returns:
      int: Result of multipllication.
  """
  result = 1
  for i in range(2, n + 1, 2):
    result *= i
    
  return result

In [23]:
N = 25
#YOUR CODE
N_double_fact = almost_double_factorial(N)

assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

### Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [24]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1])
                      
assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

### Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [34]:
def count_replacements(s, a, b):
    """ Prints the replacements that need to be made in order
    to replace all occurrences of <a> with <b> in string <s>.

    Args:
        s (string): basic string
        a (string): replaced string
        b (string): new string
    """
    count = 0
    while count <= 1000:
        if s.find(a) >= 0:
            s = s.replace(a, b)
            count += 1
        else:
            break
    print("Impossible" if count > 1000 else count)

count_replacements("ababa", "a", "b")
count_replacements("ababa", "b", "a")
count_replacements("ababa", "c", "c")
count_replacements("ababac", "c", "c")

1
1
0
Impossible


### Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [8]:
def cumsum_and_erase(A, erase=1):
    """ Returns an array with an increasing sum of the elements of the original
        array.

    Args:
        A (list): original array,
        erase (int, optional): ignored elements. Defaults to 1.

    Returns:
        list: created array.
    """
    B = []
    sum = 0
    for n in A:
        sum += n
        if sum != erase:
            B.append(sum)
        
    return B

A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

### Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [1]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences):
    """ Removes words from the text, that contains any non-alpha symbol.
    
    Args:
        sentences (list): list of sentences.

    Returns:
        list: sentences with words without non-alpha symbols.
    """
    result = []
    for sentence in sentences:
        word_list = sentence.split()
        word_list = list(filter(lambda l: l.isalpha(), word_list))
        result.append(" ".join(word_list))
    
    return result

assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

#Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [6]:
def hamming(a, b):
    """ Returns the number of mismatched characters in the same position.

    Args:
        a (string): any string,
        b (string): any string with the same length with <a>.

    Returns:
        int: mismatching characters.
    """
    if len(a) != len(b):
        raise ValueError("The strings must be the same length.")
    
    result = 0
    for i in range(0, len(a)):
        if a[i] != b[i]:
            result += 1
    return result

assert hamming("AGCT", "ACGT") == 2

### Numpy

In [7]:
import numpy as np
import random
import scipy.stats as sps

ModuleNotFoundError: No module named 'scipy'

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [25]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print("Dimension of matrix 'a':", a.ndim)
print("Dimension of matrix 'b':", b.ndim)

print("Shape of matrix 'a':", a.shape)
print("Shape of matrix 'b':", b.shape)
# ========
print(a)
print(b)

Dimension of matrix 'a': 2
Dimension of matrix 'b': 2
Shape of matrix 'a': (100, 100)
Shape of matrix 'b': (100, 100)
[[0.71432454 0.30852382 0.21474907 ... 0.37004502 0.80398597 0.14615115]
 [0.31894921 0.03687076 0.22399324 ... 0.85086116 0.92541341 0.16648341]
 [0.28954347 0.42732181 0.78920055 ... 0.19202235 0.90932493 0.27147185]
 ...
 [0.81467427 0.05976723 0.08659001 ... 0.10502486 0.35530931 0.84859568]
 [0.34253976 0.6074811  0.57128171 ... 0.01085731 0.87432133 0.55901981]
 [0.84189008 0.44870296 0.4152263  ... 0.69003146 0.20509809 0.05964402]]
[[0.75413009 0.94629248 0.92030577 ... 0.64975574 0.45478538 0.65295616]
 [0.47168757 0.84689451 0.01214723 ... 0.13086868 0.54426829 0.49972957]
 [0.40242543 0.53373656 0.1399738  ... 0.94067239 0.74359545 0.2245847 ]
 ...
 [0.86540673 0.66780618 0.63371649 ... 0.92976671 0.47857687 0.68456339]
 [0.52663152 0.66891377 0.48104681 ... 0.96407079 0.4726209  0.01956681]
 [0.92497365 0.36214699 0.76160326 ... 0.32411866 0.97161388 0.63418

In [46]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy (может помочь функция zip)
    """
    result = []
    for row_a in a:
        row_result = []
        for i in range(0, len(b)):
            col_b =  b[:, i]
            value = 0
            for j in range(0, len(a)):
                value += row_a[j] * col_b[j]
            row_result.append(value)
            
        result.append(row_result)
        
    return result

In [45]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [47]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [48]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [49]:
# проверим корректность
assert np.allclose(np.array(M1), M2)