# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [5]:
def mod_checker(x: int, mod=0):
    """ Returns lambda-function, which returns True if arg % x == mod
        and False if arg % x != mod.

    Args:
        x (int): divider
        mod (int, optional): compared value. Defaults to 0.

    Returns:
        lambda: function with 1 argument.
    """
    return lambda y: True if y % x == mod else False

mod_3 = mod_checker(3)

print(mod_3(3))
print(mod_3(4))

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4))

True
False
True


# Numpy

In [1]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [25]:
def chess_maze(n: int) -> np.array:
    """ Generates 2d-array with chess order of 0 and 1.

    Args:
        n (int): array size.

    Returns:
        np.array: 2d-array with chess order.
    """
    result = np.zeros((n, n), np.uint8)
    result[1::2, ::2] = 1 # set 1 to the even rows and odd columns
    result[::2, 1::2] = 1 # set 1 to the odd columns and even rows
    return result

print(chess_maze(8))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
#Исходный вектор 
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [35]:
def invert_values(arr: np.array, exclude_values: np.array):
    """ Invert values in the 1st array from numbers of the 2nd array.

    Args:
        arr (np.array): changed array,
        exclude_values (np.array): numbers to invert.
    """
    for i in range(len(arr)):
        if arr[i] in exclude_values:
            arr[i] = -arr[i]

arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
invert_values(arr, exclude_values)
print(arr)

arr2 = np.array([2, 4, 5, -2, 4, 3, 2])
exclude_values = np.array([2, 4])
invert_values(arr2, exclude_values)
print(arr2)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[-2 -4  5 -2 -4  3 -2]


## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
#Исходный вектор 
arr = np.random.uniform(low=10, high=100,size=20)
#Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [29]:
import math

def arr_to_int(arr: np.array):
    """ Prints 7-times array without fractional part using different methods.

    Args:
        arr (np.array): array with floats.
    """
    print(arr.astype(int))
    print(np.array([int(num) for num in arr]))
    print(np.array([math.floor(num) for num in arr]))
    print(np.array([math.trunc(num) for num in arr]))
    print(np.array([num - num % 1 for num in arr]))
    print(np.array([num // 1 for num in arr]))
    print(np.array([float(num[:num.find('.')]) for num in arr.astype(str)]))
    
arr = np.random.uniform(low=10, high=100, size=20)
arr_to_int(arr)

[33 30 80 18 19 42 32 99 10 45 42 44 43 16 27 36 90 95 20 47]
[33 30 80 18 19 42 32 99 10 45 42 44 43 16 27 36 90 95 20 47]
[33 30 80 18 19 42 32 99 10 45 42 44 43 16 27 36 90 95 20 47]
[33 30 80 18 19 42 32 99 10 45 42 44 43 16 27 36 90 95 20 47]
[33. 30. 80. 18. 19. 42. 32. 99. 10. 45. 42. 44. 43. 16. 27. 36. 90. 95.
 20. 47.]
[33. 30. 80. 18. 19. 42. 32. 99. 10. 45. 42. 44. 43. 16. 27. 36. 90. 95.
 20. 47.]
[33. 30. 80. 18. 19. 42. 32. 99. 10. 45. 42. 44. 43. 16. 27. 36. 90. 95.
 20. 47.]


## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [6]:
def rand_matrix(N: int, p: int) -> np.array:
    """ Generates 2D zero-array with <p> random numbers.

    Args:
        N (int): length of the side,
        p (int): number of random values.

    Raises:
        ValueError: checks number of random values.

    Returns:
        np.array: matrix with random values.
    """
    if p > N**2:
        raise ValueError(f'Number of random values must be less than {N**2}')
    
    result = np.zeros((N, N))
    indexes = np.random.choice(N**2, size=p, replace=False)
    for i in indexes:
        result[i // N, i % N] = np.random.randint(1, 100)
    return result

rand_matrix(N=6, p=4)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 49.,  0.,  0., 27.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 52.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 99.,  0.,  0.]])

# Pandas

In [2]:
import pandas as pd

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [71]:
my_data = pd.DataFrame(
    data=[
        ['B', 18.],
        ['B', 20.],
        ['C', 10.],
        ['C', -10.]
    ],
    columns=['type', 'value'])

# При использовании метода memory_usage(), можно поместить значение
# в переменную, чтобы дальше с ней можно было работать.
mem1 = my_data.memory_usage().sum()
print(f'Initial size of data frame - {mem1} bytes')

my_data['type'] = my_data['type'].astype('category')
mem2 = my_data.memory_usage().sum()
print(f'Size after changing type to category - {mem2} bytes')

my_data['value'] = my_data['value'].astype(np.float16)
mem3 = my_data.memory_usage().sum()
print(f'Size after changing value type - {mem3} bytes')

Initial size of data frame - 192 bytes
Size after changing type to category - 288 bytes
Size after changing value type - 264 bytes


# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [11]:
size = 10_000

my_data = pd.DataFrame()
my_data['type'] = np.random.choice(
    ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], size)
my_data['value'] = np.array(np.random.randint(-100, 100, size), dtype=np.float64)

# При использовании метода memory_usage(), можно поместить значение
# в переменную, чтобы дальше с ней можно было работать.
mem1 = my_data.memory_usage().sum()
print(f'Initial size of data frame - {mem1} bytes')

my_data['type'] = my_data['type'].astype('category')
mem2 = my_data.memory_usage().sum()
print(f'Size after changing type to category - {mem2} bytes')

my_data['value'] = my_data['value'].astype(np.float16)
mem3 = my_data.memory_usage().sum()
print(f'Size after changing value type - {mem3} bytes')

k_mem = round(mem1 / mem3, 2)
print(f'Size of data frame reduced in {k_mem}')

Initial size of data frame - 160128 bytes
Size after changing type to category - 90508 bytes
Size after changing value type - 30508 bytes
Size of data frame reduced in 5.25


#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [12]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [16]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [39]:
subset_1 = df.loc[:19, ['V1', 'V3']]

filter = (df.index != 1) & (df.index != 2) & (df.index != 17)
subset_2 = df[filter].loc[:, ['V2', 'V4']]

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [42]:
filter = (df['V1'] > 0) & (df['V3'] == 'A')
subset_3 = df[filter]

filter = (df['V2'] != 10) | (df['V4'] >= 1)
subset_4 = df[filter]

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [45]:
df['V5'] = df['V1'] + df['V4']
df['V6'] = np.log(df['V2'])

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [51]:
df.rename(columns={'V1':'session_value', 'V2':'group', 
                   'V3':'time', 'V4':'n_users'}, inplace=True)

# Задание 12
В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [61]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [74]:
my_stat['session_value'] = my_stat['session_value'].fillna(0)

filter = my_stat['n_users'] > 0
median = my_stat[filter]['n_users'].median()
filter = my_stat['n_users'] < 0
my_stat.loc[filter, 'n_users'] = median